#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: PR Build (Camel 4)

on:
  pull_request:
    branches:
      - camel-4.0.x
    paths-ignore:
      - .github/**
      - README.md
      - SECURITY.md
      - Jenkinsfile
      - Jenkinsfile.*
      - NOTICE.txt

permissions:  
  contents: read

jobs:
  build:
    if: github.repository == 'apache/camel'
    permissions:
      issues: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
      - id: install-packages
        uses: ./.github/actions/install-packages
      - id: install-mvnd
        uses: ./.github/actions/install-mvnd
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: maven build
        run: ./mvnw -l build.log -Dquickly install
      - name: archive logs
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
        if: always()
        with:
          name: build.log
          path: build.log
      - name: Fail if there are uncommitted changes
        shell: bash
        run: |
          [[ -z $(git status --porcelain) ]] || { echo 'There are uncommitted changes'; git status; echo; echo; git diff; exit 1; }
      - name: mvn test
        uses: ./.github/actions/incremental-build
        with:
          mode: test
          pr-id: ${{ github.event.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-mvnd-install: 'true'
          artifact-upload-suffix: java-${{ matrix.java }}
