#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Build and test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/**
      - README.md
      - SECURITY.md
      - Jenkinsfile
      - Jenkinsfile.*
      - NOTICE.txt

permissions:
  contents: read

jobs:
  build:
    if: github.repository == 'apache/camel'
    permissions:
      issues: write
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        java: ['17']
        experimental: [ false ]
        include:
          - java: '21'
            experimental: true

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - id: install-packages
        uses: ./.github/actions/install-packages
      - id: install-mvnd
        uses: ./.github/actions/install-mvnd
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: maven build
        run: ./etc/scripts/regen.sh
      - name: archive logs
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: always()
        with:
          name: build-${{ matrix.java }}.log
          path: build.log
      - name: Fail if there are uncommitted changes
        shell: bash
        run: |
          [[ -z $(git status --porcelain) ]] || { echo 'There are uncommitted changes'; git status; echo; echo; git diff; exit 1; }
      - name: mvn test
        uses: ./.github/actions/incremental-build
        with:
          mode: test
          pr-id: ${{ github.event.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-mvnd-install: 'true'
          artifact-upload-suffix: java-${{ matrix.java }}
      - name: mvn test parent pom dependencies changed
        uses: ./.github/actions/detect-dependencies
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
